/**
 * In-memory seed data for MockAppsScriptAdapter. Mirrors realistic institutional
 * data from MASTER HANDOFF §18 for Mi Trabajo and RRHH Golden Workflow.
 * Disappears once the real Apps Script backend is wired via HttpAppsScriptAdapter.
 *
 * Demo user (admin): USR-VRAF-001 / m.villalta@upes.edu.sv
 * Demo user (ops):   USR-RH-012  / j.ramirez@upes.edu.sv
 */
import type {
  Actividad,
  Evidencia,
  Formulario,
  Indicador,
  PlanEstrategico,
  ObjetivoEstrategico,
  ProyectoEstrategico,
  ProcesoInstitucional,
  Solicitud,
  Unidad,
  Usuario,
} from "@/types/entities";
import type {
  Empleado,
  CapacitacionEmpleado,
  EvaluacionDesempeno,
  SolicitudContratacion,
} from "@/types/hr";
import type { Notificacion } from "@/types/notifications";

export const mockUnidades: Unidad[] = [
  { id: "vraf",    nombre: "Vicerrectoría Administrativa y Financiera" },
  { id: "rrhh",    nombre: "Recursos Humanos" },
  { id: "conta",   nombre: "Contabilidad" },
  { id: "compras", nombre: "Compras" },
  { id: "mant",    nombre: "Mantenimiento e Infraestructura" },
  { id: "salud",   nombre: "Salud y Seguridad Ocupacional" },
];

export const mockUsuarios: Usuario[] = [
  {
    id: "USR-VRAF-001",
    nombre: "M. Villalta",
    email: "m.villalta@upes.edu.sv",
    unidadId: "vraf",
    rol: "ADMIN",
    activo: true,
    avatarInitials: "MV",
  },
  {
    id: "USR-RH-012",
    nombre: "J. Ramírez",
    email: "j.ramirez@upes.edu.sv",
    unidadId: "rrhh",
    rol: "HEAD",
    activo: true,
    avatarInitials: "JR",
  },
];

export const mockPlanes: PlanEstrategico[] = [
  {
    id: "PLAN-2026-2030",
    nombre: "Plan Estratégico Institucional 2026-2030",
    periodoInicio: "2026-01-01",
    periodoFin: "2030-12-31",
  },
];

export const mockObjetivos: ObjetivoEstrategico[] = [
  {
    id: "OBJ-001",
    planId: "PLAN-2026-2030",
    nombre: "Fortalecer la gestión administrativa y financiera institucional",
  },
  {
    id: "OBJ-002",
    planId: "PLAN-2026-2030",
    nombre: "Modernizar los procesos de talento humano",
  },
];

export const mockProyectos: ProyectoEstrategico[] = [
  {
    id: "PROY-001",
    objetivoId: "OBJ-002",
    nombre: "Modernización de procesos de talento humano",
    unidadId: "rrhh",
  },
  {
    id: "PROY-002",
    objetivoId: "OBJ-001",
    nombre: "Eficiencia financiera institucional",
    unidadId: "vraf",
  },
  {
    id: "PROY-003",
    objetivoId: "OBJ-001",
    nombre: "Control y cumplimiento normativo",
    unidadId: "vraf",
  },
];

export const mockProcesos: ProcesoInstitucional[] = [
  // ── RRHH processes ────────────────────────────────────────────────────────
  {
    id: "PROC-RH-26-001",
    proyectoId: "PROY-001",
    unidadId: "rrhh",
    nombre: "Contratación de Personal — Analista TI",
    tipo: "misional",
    objetivo: "Cubrir plaza de Analista de Tecnologías de la Información mediante proceso competitivo",
    alcance: "Desde la solicitud de plaza hasta la inducción del nuevo colaborador",
    responsableId: "USR-RH-012",
    estado: "activo",
    avancePct: 40,
    semaforo: "amarillo",
    fechaInicio: "2026-06-01",
    fechaLimite: "2026-07-31",
    slaDias: 60,
    prioridad: "alta",
    ultimaActualizacion: "2026-07-09T10:00:00.000Z",
    createdAt: "2026-06-01T08:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "PROC-RH-26-002",
    proyectoId: "PROY-001",
    unidadId: "rrhh",
    nombre: "Plan de Capacitación Institucional 2026",
    tipo: "estrategico",
    objetivo: "Fortalecer competencias del personal mediante programa de formación estructurado",
    alcance: "Todo el personal activo de la institución",
    responsableId: "USR-RH-012",
    estado: "activo",
    avancePct: 65,
    semaforo: "verde",
    fechaInicio: "2026-01-01",
    fechaLimite: "2026-12-31",
    slaDias: 365,
    prioridad: "alta",
    ultimaActualizacion: "2026-07-05T10:00:00.000Z",
    createdAt: "2026-01-01T08:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "PROC-RH-26-003",
    proyectoId: "PROY-001",
    unidadId: "rrhh",
    nombre: "Evaluación de Desempeño Semestral S1-2026",
    tipo: "misional",
    objetivo: "Medir y documentar el desempeño del personal en el primer semestre",
    alcance: "Todo el personal activo con más de 3 meses en la institución",
    responsableId: "USR-RH-012",
    estado: "completado",
    avancePct: 100,
    semaforo: "verde",
    fechaInicio: "2026-06-15",
    fechaLimite: "2026-07-15",
    slaDias: 30,
    prioridad: "media",
    ultimaActualizacion: "2026-07-09T12:00:00.000Z",
    createdAt: "2026-06-15T08:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "PROC-RH-26-004",
    proyectoId: "PROY-001",
    unidadId: "rrhh",
    nombre: "Clima Organizacional 2026",
    tipo: "misional",
    objetivo: "Medir la satisfacción y el clima organizacional institucional",
    alcance: "Personal activo, mediante encuesta anónima en línea",
    responsableId: "USR-RH-012",
    estado: "borrador",
    avancePct: 10,
    semaforo: "amarillo",
    fechaInicio: "2026-08-01",
    fechaLimite: "2026-09-30",
    slaDias: 60,
    prioridad: "media",
    ultimaActualizacion: "2026-07-09T08:00:00.000Z",
    createdAt: "2026-07-01T08:00:00.000Z",
    deletedAt: null,
  },

  // ── VRAF processes (responsable: M. Villalta / admin) ────────────────────
  {
    id: "PROC-VRAF-26-001",
    proyectoId: "PROY-002",
    unidadId: "vraf",
    nombre: "Presupuesto Institucional 2027",
    tipo: "estrategico",
    objetivo: "Elaborar y someter para aprobación el presupuesto del ejercicio 2027",
    alcance: "Desde la recopilación de requerimientos hasta la aprobación del Consejo Directivo",
    responsableId: "USR-VRAF-001",
    estado: "activo",
    avancePct: 55,
    semaforo: "verde",
    fechaInicio: "2026-06-15",
    fechaLimite: "2026-09-30",
    slaDias: 107,
    prioridad: "alta",
    ultimaActualizacion: "2026-07-08T14:30:00.000Z",
    createdAt: "2026-06-15T08:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "PROC-VRAF-26-002",
    proyectoId: "PROY-003",
    unidadId: "vraf",
    nombre: "Auditoría Financiera Q2 2026",
    tipo: "apoyo",
    objetivo: "Validar la correcta ejecución presupuestaria del segundo trimestre",
    alcance: "Verificación de estados financieros, registros contables y cumplimiento normativo",
    responsableId: "USR-VRAF-001",
    estado: "en_riesgo",
    avancePct: 20,
    semaforo: "rojo",
    fechaInicio: "2026-05-01",
    fechaLimite: "2026-07-05",
    slaDias: 65,
    prioridad: "critica",
    ultimaActualizacion: "2026-07-07T16:00:00.000Z",
    createdAt: "2026-05-01T08:00:00.000Z",
    deletedAt: null,
  },
  {
    id: "PROC-VRAF-26-003",
    proyectoId: "PROY-002",
    unidadId: "vraf",
    nombre: "Licitación Suministros de Oficina",
    tipo: "operativo",
    objetivo: "Garantizar el abastecimiento de suministros a todas las unidades administrativas",
    alcance: "Proceso de licitación pública desde las bases hasta la adjudicación",
    responsableId: "USR-VRAF-001",
    estado: "activo",
    avancePct: 38,
    semaforo: "amarillo",
    fechaInicio: "2026-06-20",
    fechaLimite: "2026-08-15",
    slaDias: 56,
    prioridad: "media",
    ultimaActualizacion: "2026-07-06T10:00:00.000Z",
    createdAt: "2026-06-20T08:00:00.000Z",
    deletedAt: null,
  },
];

export const mockActividades: Actividad[] = [
  // ── RRHH hiring workflow activities (Golden Workflow) ────────────────────
  { id: "ACT-RH-001-01", procesoId: "PROC-RH-26-001", etapaId: "solicitud",            nombre: "Completar formulario de solicitud de plaza",         descripcion: "El jefe de unidad completa la justificación y características del puesto",   responsableId: "USR-VRAF-001", prioridad: "alta",  estado: "completada", orden: 1 },
  { id: "ACT-RH-001-02", procesoId: "PROC-RH-26-001", etapaId: "solicitud",            nombre: "Aprobación de jefatura solicitante",                 descripcion: "Jefatura inmediata firma la solicitud",                                       responsableId: "USR-VRAF-001", prioridad: "alta",  estado: "completada", orden: 2 },
  { id: "ACT-RH-001-03", procesoId: "PROC-RH-26-001", etapaId: "revision",             nombre: "Revisión técnica por RRHH",                         descripcion: "RRHH verifica requisitos, presupuesto y clasificación del cargo",             responsableId: "USR-RH-012",   prioridad: "alta",  estado: "completada", orden: 3 },
  { id: "ACT-RH-001-04", procesoId: "PROC-RH-26-001", etapaId: "revision",             nombre: "Validación de disponibilidad presupuestaria",        descripcion: "Confirmar partida presupuestaria disponible con VRAF",                        responsableId: "USR-RH-012",   prioridad: "alta",  estado: "completada", orden: 4 },
  { id: "ACT-RH-001-05", procesoId: "PROC-RH-26-001", etapaId: "publicacion",          nombre: "Elaborar perfil del puesto",                        descripcion: "Redactar requisitos, funciones, competencias y condiciones laborales",        responsableId: "USR-RH-012",   prioridad: "media", estado: "completada", orden: 5 },
  { id: "ACT-RH-001-06", procesoId: "PROC-RH-26-001", etapaId: "publicacion",          nombre: "Publicar convocatoria interna y externa",           descripcion: "Difundir en medios institucionales y tablón de empleos",                     responsableId: "USR-RH-012",   prioridad: "media", estado: "completada", orden: 6 },
  { id: "ACT-RH-001-07", procesoId: "PROC-RH-26-001", etapaId: "recepcion_candidatos", nombre: "Recibir y clasificar aplicaciones",                 descripcion: "Gestionar CVs recibidos y crear expediente por candidato",                   responsableId: "USR-RH-012",   prioridad: "alta",  estado: "completada", orden: 7 },
  { id: "ACT-RH-001-08", procesoId: "PROC-RH-26-001", etapaId: "evaluacion",           nombre: "Aplicar pruebas técnicas y psicológicas",           descripcion: "Evaluar competencias técnicas y perfil psicológico de candidatos preseleccionados", responsableId: "USR-RH-012", prioridad: "alta",  estado: "en_progreso", orden: 8 },
  { id: "ACT-RH-001-09", procesoId: "PROC-RH-26-001", etapaId: "evaluacion",           nombre: "Calificar y ordenar resultados",                   descripcion: "Puntuar pruebas y elaborar ranking de candidatos",                           responsableId: "USR-RH-012",   prioridad: "alta",  estado: "pendiente",  orden: 9 },
  { id: "ACT-RH-001-10", procesoId: "PROC-RH-26-001", etapaId: "entrevistas",          nombre: "Entrevista con panel directivo",                   descripcion: "Panel compuesto por jefe de unidad, RRHH y Vicerrector",                     responsableId: "USR-RH-012",   prioridad: "alta",  estado: "pendiente",  orden: 10 },
  { id: "ACT-RH-001-11", procesoId: "PROC-RH-26-001", etapaId: "seleccion",            nombre: "Seleccionar candidato finalista",                  descripcion: "El panel elige al candidato y documenta la decisión",                        responsableId: "USR-RH-012",   prioridad: "alta",  estado: "pendiente",  orden: 11 },
  { id: "ACT-RH-001-12", procesoId: "PROC-RH-26-001", etapaId: "aprobacion",           nombre: "Aprobación de Rectoría",                          descripcion: "Resolución de Rectoría autorizando la contratación",                         responsableId: "USR-VRAF-001", prioridad: "alta",  estado: "pendiente",  orden: 12 },
  { id: "ACT-RH-001-13", procesoId: "PROC-RH-26-001", etapaId: "contratacion",         nombre: "Elaborar y firmar contrato",                      descripcion: "Redactar contrato, revisión legal, firmas y distribución de copias",          responsableId: "USR-RH-012",   prioridad: "alta",  estado: "pendiente",  orden: 13 },
  { id: "ACT-RH-001-14", procesoId: "PROC-RH-26-001", etapaId: "onboarding",           nombre: "Inducción institucional",                         descripcion: "Presentación de misión, visión, reglamentos y recorrido por instalaciones",   responsableId: "USR-RH-012",   prioridad: "media", estado: "pendiente",  orden: 14 },
  { id: "ACT-RH-001-15", procesoId: "PROC-RH-26-001", etapaId: "onboarding",           nombre: "Configurar accesos y equipo",                     descripcion: "Habilitar credenciales de sistema, asignar equipo de trabajo y espacio",     responsableId: "USR-RH-012",   prioridad: "media", estado: "pendiente",  orden: 15 },

  // ── VRAF: Presupuesto activities ──────────────────────────────────────────
  {
    id: "ACT-VRAF-26-001-01",
    procesoId: "PROC-VRAF-26-001",
    nombre: "Recopilación de requerimientos por unidad",
    descripcion: "Consolidar los requerimientos presupuestarios de todas las unidades administrativas",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "completada",
    orden: 1,
  },
  {
    id: "ACT-VRAF-26-001-02",
    procesoId: "PROC-VRAF-26-001",
    nombre: "Análisis de ejecución presupuestaria 2026",
    descripcion: "Revisar la ejecución actual y proyectar cierres de año",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "en_progreso",
    orden: 2,
  },
  {
    id: "ACT-VRAF-26-001-03",
    procesoId: "PROC-VRAF-26-001",
    nombre: "Validación de partidas con Rectoría",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "pendiente",
    orden: 3,
  },

  // ── VRAF: Auditoría activities (overdue process) ──────────────────────────
  {
    id: "ACT-VRAF-26-002-01",
    procesoId: "PROC-VRAF-26-002",
    nombre: "Revisión de registros contables Q2",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "en_progreso",
    orden: 1,
  },
  {
    id: "ACT-VRAF-26-002-02",
    procesoId: "PROC-VRAF-26-002",
    nombre: "Preparación de informe de auditoría",
    descripcion: "Consolidar hallazgos y redactar el informe final para el Consejo",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "pendiente",
    orden: 2,
  },

  // ── VRAF: Licitación activities ───────────────────────────────────────────
  {
    id: "ACT-VRAF-26-003-01",
    procesoId: "PROC-VRAF-26-003",
    nombre: "Elaboración de bases de licitación",
    responsableId: "USR-VRAF-001",
    prioridad: "media",
    estado: "completada",
    orden: 1,
  },
  {
    id: "ACT-VRAF-26-003-02",
    procesoId: "PROC-VRAF-26-003",
    nombre: "Publicación en COMPRASAL",
    responsableId: "USR-VRAF-001",
    prioridad: "alta",
    estado: "pendiente",
    orden: 2,
  },
];

export const mockEvidencias: Evidencia[] = [
  // ── RRHH evidences ────────────────────────────────────────────────────────
  {
    id: "EV-ACT-RH-001-03-01",
    actividadId: "ACT-PROC-RH-26-001-03",
    nombre: "Perfil del puesto",
    tipo: "documento",
    obligatoria: true,
    estado: "cargada",
    version: 1,
    responsableId: "USR-RH-012",
    fechaCarga: "2026-07-08T15:00:00.000Z",
  },
  {
    id: "EV-ACT-RH-001-03-02",
    actividadId: "ACT-PROC-RH-26-001-03",
    nombre: "Autorización de Recursos Humanos",
    tipo: "acta",
    obligatoria: true,
    estado: "pendiente",
    version: 1,
    responsableId: "USR-RH-012",
  },

  // ── VRAF evidences ────────────────────────────────────────────────────────
  {
    id: "EV-VRAF-001-02-01",
    actividadId: "ACT-VRAF-26-001-02",
    nombre: "Informe de ejecución presupuestaria 2026",
    tipo: "informe",
    obligatoria: true,
    estado: "pendiente",
    version: 1,
    responsableId: "USR-VRAF-001",
  },
  {
    id: "EV-VRAF-001-02-02",
    actividadId: "ACT-VRAF-26-001-02",
    nombre: "Proyección de cierre 2026",
    tipo: "documento",
    obligatoria: true,
    estado: "pendiente",
    version: 1,
    responsableId: "USR-VRAF-001",
  },
  {
    id: "EV-VRAF-002-01-01",
    actividadId: "ACT-VRAF-26-002-01",
    nombre: "Registros contables Q2",
    tipo: "registro",
    obligatoria: true,
    estado: "cargada",
    version: 2,
    responsableId: "USR-VRAF-001",
    fechaCarga: "2026-07-01T10:00:00.000Z",
    observaciones: "Versión 2 corregida tras revisión inicial",
  },
  {
    id: "EV-VRAF-002-02-01",
    actividadId: "ACT-VRAF-26-002-02",
    nombre: "Informe de auditoría Q2 (borrador)",
    tipo: "informe",
    obligatoria: true,
    estado: "pendiente",
    version: 1,
    responsableId: "USR-VRAF-001",
  },
];

export const mockIndicadores: Indicador[] = [
  // ── RRHH KPI ──────────────────────────────────────────────────────────────
  {
    id: "KPI-RH-001",
    procesoId: "PROC-RH-26-001",
    nombre: "Tiempo de contratación",
    objetivo: "Medir la duración total del proceso de contratación",
    descripcion: "Días transcurridos desde la solicitud de plaza hasta la firma de contrato",
    categoria: "desempeno",
    formula: "fechaFirma - fechaSolicitud",
    unidadMedida: "días",
    meta: 45,
    valorActual: 52,
    frecuencia: "mensual",
    responsableId: "USR-RH-012",
    fuenteInformacion: "Registro del proceso",
    dashboardDestino: "Dashboard RRHH",
    reporteDestino: "Informe mensual contratación",
    semaforo: "amarillo",
    tendencia: "baja",
    ultimaActualizacion: "2026-07-09T10:00:00.000Z",
  },

  // ── VRAF KPIs ─────────────────────────────────────────────────────────────
  {
    id: "KPI-VRAF-001",
    procesoId: "PROC-VRAF-26-001",
    nombre: "Eficiencia de ejecución presupuestaria",
    objetivo: "Medir el porcentaje de ejecución del presupuesto aprobado",
    descripcion: "Relación entre el presupuesto ejecutado y el aprobado, expresada en porcentaje",
    categoria: "gestion",
    formula: "(presupuestoEjecutado / presupuestoAprobado) * 100",
    unidadMedida: "%",
    meta: 85,
    valorActual: 78,
    frecuencia: "trimestral",
    responsableId: "USR-VRAF-001",
    fuenteInformacion: "Sistema contable institucional",
    dashboardDestino: "Dashboard VRAF",
    reporteDestino: "Informe trimestral VRAF",
    semaforo: "amarillo",
    tendencia: "sube",
    ultimaActualizacion: "2026-07-05T09:00:00.000Z",
  },
  {
    id: "KPI-VRAF-002",
    procesoId: "PROC-VRAF-26-002",
    nombre: "Tiempo de respuesta financiera",
    objetivo: "Garantizar la agilidad en la respuesta a solicitudes de carácter financiero",
    descripcion: "Días promedio desde la recepción de una solicitud hasta su resolución",
    categoria: "desempeno",
    formula: "promedio(fechaRespuesta - fechaSolicitud)",
    unidadMedida: "días",
    meta: 5,
    valorActual: 8,
    frecuencia: "mensual",
    responsableId: "USR-VRAF-001",
    fuenteInformacion: "Registro de solicitudes",
    dashboardDestino: "Dashboard VRAF",
    reporteDestino: "Informe mensual VRAF",
    semaforo: "rojo",
    tendencia: "baja",
    ultimaActualizacion: "2026-07-09T08:00:00.000Z",
  },
];

export const mockSolicitudes: Solicitud[] = [
  {
    id: "SOL-COMP-26-047",
    procesoId: "PROC-RH-26-001",
    unidadId: "compras",
    asunto: "Compra de equipo de cómputo para nueva plaza",
    solicitanteId: "USR-RH-012",
    responsableId: "USR-VRAF-001",
    estado: "en_atencion",
    fechaCreacion: "2026-07-05T09:00:00.000Z",
  },
  {
    id: "SOL-VRAF-26-012",
    procesoId: "PROC-VRAF-26-003",
    unidadId: "vraf",
    asunto: "Aprobación de bases de licitación de suministros",
    solicitanteId: "USR-VRAF-001",
    responsableId: "USR-VRAF-001",
    estado: "abierta",
    fechaCreacion: "2026-07-08T14:00:00.000Z",
  },
];

// ─── HR Domain Entities (Sprint 4) ───────────────────────────────────────────

export const mockEmpleados: Empleado[] = [
  {
    id: "EMP-RH-26-001",
    usuarioId: "USR-RH-012",
    unidadId: "rrhh",
    nombres: "Juan Carlos",
    apellidos: "Ramírez Morales",
    email: "j.ramirez@upes.edu.sv",
    dui: "01234567-8",
    fechaNacimiento: "1985-03-15",
    telefono: "+503 7890-1234",
    cargo: "Jefe de Recursos Humanos",
    categoria: "ejecutivo",
    tipoContrato: "indefinido",
    fechaIngreso: "2018-01-15",
    estado: "activo",
    salario: 2800,
    diasVacacionesPendientes: 12,
    evaluacionUltimaPuntuacion: 88,
    capacitacionesCompletas: 7,
    avatarInitials: "JR",
    createdAt: "2018-01-15T08:00:00.000Z",
  },
  {
    id: "EMP-RH-26-002",
    unidadId: "rrhh",
    nombres: "Ana María",
    apellidos: "García López",
    email: "a.garcia@upes.edu.sv",
    dui: "12345678-9",
    cargo: "Analista de Recursos Humanos",
    categoria: "profesional",
    tipoContrato: "indefinido",
    fechaIngreso: "2020-06-01",
    estado: "activo",
    salario: 1800,
    diasVacacionesPendientes: 5,
    evaluacionUltimaPuntuacion: 92,
    capacitacionesCompletas: 4,
    avatarInitials: "AG",
    createdAt: "2020-06-01T08:00:00.000Z",
  },
  {
    id: "EMP-RH-26-003",
    unidadId: "rrhh",
    nombres: "Carlos Ernesto",
    apellidos: "Henríquez Vásquez",
    email: "c.henriquez@upes.edu.sv",
    dui: "23456789-0",
    cargo: "Analista de Nómina",
    categoria: "profesional",
    tipoContrato: "indefinido",
    fechaIngreso: "2021-02-15",
    estado: "activo",
    salario: 1650,
    diasVacacionesPendientes: 8,
    evaluacionUltimaPuntuacion: 85,
    capacitacionesCompletas: 3,
    avatarInitials: "CH",
    createdAt: "2021-02-15T08:00:00.000Z",
  },
  {
    id: "EMP-RH-26-004",
    unidadId: "rrhh",
    nombres: "María Alejandra",
    apellidos: "Torres de Quijano",
    email: "m.torres@upes.edu.sv",
    dui: "34567890-1",
    cargo: "Coordinadora de Bienestar Laboral",
    categoria: "profesional",
    tipoContrato: "indefinido",
    fechaIngreso: "2019-08-01",
    estado: "activo",
    salario: 1900,
    diasVacacionesPendientes: 3,
    evaluacionUltimaPuntuacion: 95,
    capacitacionesCompletas: 9,
    avatarInitials: "MT",
    createdAt: "2019-08-01T08:00:00.000Z",
  },
  {
    id: "EMP-RH-26-005",
    unidadId: "rrhh",
    nombres: "Roberto Alfredo",
    apellidos: "Alfaro Mejía",
    email: "r.alfaro@upes.edu.sv",
    dui: "45678901-2",
    cargo: "Auxiliar Administrativo RRHH",
    categoria: "administrativo",
    tipoContrato: "plazo_fijo",
    fechaIngreso: "2024-01-15",
    fechaEgreso: "2026-12-31",
    estado: "activo",
    salario: 700,
    diasVacacionesPendientes: 0,
    evaluacionUltimaPuntuacion: 78,
    capacitacionesCompletas: 1,
    avatarInitials: "RA",
    createdAt: "2024-01-15T08:00:00.000Z",
  },
  {
    id: "EMP-RH-26-006",
    unidadId: "rrhh",
    nombres: "Sofía Beatriz",
    apellidos: "Méndez Castillo",
    email: "s.mendez@upes.edu.sv",
    dui: "56789012-3",
    cargo: "Analista de Selección de Personal",
    categoria: "profesional",
    tipoContrato: "plazo_fijo",
    fechaIngreso: "2025-01-01",
    fechaEgreso: "2026-12-31",
    estado: "activo",
    salario: 1550,
    diasVacacionesPendientes: 2,
    capacitacionesCompletas: 0,
    avatarInitials: "SM",
    createdAt: "2025-01-01T08:00:00.000Z",
  },
];

export const mockCapacitaciones: CapacitacionEmpleado[] = [
  {
    id: "CAP-RH-26-001",
    empleadoId: "EMP-RH-26-001",
    nombre: "Gestión del Talento Humano por Competencias",
    tipo: "externa",
    proveedor: "INCAE Business School",
    fechaInicio: "2026-03-10",
    fechaFin: "2026-03-14",
    duracionHoras: 40,
    estado: "completada",
    certificado: true,
  },
  {
    id: "CAP-RH-26-002",
    empleadoId: "EMP-RH-26-002",
    nombre: "Excel Avanzado para RRHH",
    tipo: "virtual",
    proveedor: "LinkedIn Learning",
    fechaInicio: "2026-06-01",
    fechaFin: "2026-06-30",
    duracionHoras: 20,
    estado: "completada",
    certificado: true,
  },
  {
    id: "CAP-RH-26-003",
    empleadoId: "EMP-RH-26-004",
    nombre: "Bienestar Organizacional y Salud Mental",
    tipo: "externa",
    proveedor: "OPS/OMS El Salvador",
    fechaInicio: "2026-08-15",
    fechaFin: "2026-08-19",
    duracionHoras: 30,
    estado: "programada",
    certificado: false,
  },
  {
    id: "CAP-RH-26-004",
    empleadoId: "EMP-RH-26-003",
    nombre: "Nómina Electrónica y Obligaciones Laborales 2026",
    tipo: "externa",
    proveedor: "INSAFORP",
    fechaInicio: "2026-05-05",
    fechaFin: "2026-05-09",
    duracionHoras: 32,
    estado: "completada",
    certificado: true,
  },
  {
    id: "CAP-RH-26-005",
    empleadoId: "EMP-RH-26-001",
    nombre: "Técnicas de Entrevista por Competencias",
    tipo: "virtual",
    proveedor: "SHRM Online",
    fechaInicio: "2026-07-15",
    fechaFin: "2026-07-19",
    duracionHoras: 16,
    estado: "programada",
    certificado: false,
  },
];

export const mockEvaluaciones: EvaluacionDesempeno[] = [
  {
    id: "EVAL-RH-26-001",
    empleadoId: "EMP-RH-26-001",
    periodo: "2026-S1",
    evaluadorId: "USR-VRAF-001",
    puntuacion: 88,
    nivel: "bueno",
    fortalezas: "Liderazgo efectivo, gestión de conflictos, planificación estratégica",
    areasOportunidad: "Mejorar habilidades en analítica de datos RRHH",
    metasSiguientePeriodo: "Implementar evaluación 360°, digitalizar expedientes de personal",
    estado: "aprobada",
    fecha: "2026-07-01T10:00:00.000Z",
  },
  {
    id: "EVAL-RH-26-002",
    empleadoId: "EMP-RH-26-002",
    periodo: "2026-S1",
    evaluadorId: "EMP-RH-26-001",
    puntuacion: 92,
    nivel: "excelente",
    fortalezas: "Precisión en procesos, capacidad de análisis, atención al detalle",
    areasOportunidad: "Fortalecer comunicación interdepartamental",
    estado: "aprobada",
    fecha: "2026-07-03T10:00:00.000Z",
  },
  {
    id: "EVAL-RH-26-003",
    empleadoId: "EMP-RH-26-003",
    periodo: "2026-S1",
    evaluadorId: "EMP-RH-26-001",
    puntuacion: 85,
    nivel: "bueno",
    fortalezas: "Exactitud en cálculo de nómina, cumplimiento de plazos",
    areasOportunidad: "Automatización de reportes periódicos",
    estado: "aprobada",
    fecha: "2026-07-04T10:00:00.000Z",
  },
  {
    id: "EVAL-RH-26-004",
    empleadoId: "EMP-RH-26-004",
    periodo: "2026-S1",
    evaluadorId: "EMP-RH-26-001",
    puntuacion: 95,
    nivel: "excelente",
    fortalezas: "Empatía excepcional, iniciativa, coordinación de actividades de bienestar",
    areasOportunidad: "Documentar metodologías para replicabilidad",
    estado: "aprobada",
    fecha: "2026-07-04T10:00:00.000Z",
  },
];

export const mockSolicitudesContratacion: SolicitudContratacion[] = [
  {
    id: "CONT-26-001",
    unidadId: "rrhh",
    procesoId: "PROC-RH-26-001",
    cargo: "Analista de Tecnologías de la Información",
    categoria: "profesional",
    justificacion: "Se requiere personal técnico especializado para la implementación del nuevo SIRH y modernización de procesos digitales institucionales.",
    tipoContrato: "indefinido",
    salarioPropuesto: 1800,
    responsableId: "USR-RH-012",
    solicitanteId: "USR-VRAF-001",
    etapaActual: "evaluacion",
    candidatos: 12,
    fechaCreacion: "2026-06-01T08:00:00.000Z",
    fechaObjetivo: "2026-07-31T00:00:00.000Z",
    observaciones: "Proceso urgente — impacto directo en proyecto de transformación digital institucional",
  },
];

export const mockNotificaciones: Notificacion[] = [
  {
    id: "NOTIF-001",
    usuarioId: "USR-RH-012",
    titulo: "Actividad en progreso",
    mensaje: "La actividad 'Aplicar pruebas técnicas y psicológicas' está en progreso desde hace 2 días",
    categoria: "actividad",
    prioridad: "media",
    leida: false,
    accionUrl: "/ws/rrhh/procesos",
    entidadTipo: "actividad",
    entidadId: "ACT-RH-001-08",
    creadoEn: "2026-07-10T09:30:00.000Z",
  },
  {
    id: "NOTIF-002",
    usuarioId: "USR-RH-012",
    titulo: "SLA próximo a vencer",
    mensaje: "El proceso de contratación CONT-26-001 debe completarse antes del 31 de julio",
    categoria: "solicitud",
    prioridad: "alta",
    leida: false,
    accionUrl: "/ws/rrhh/contratacion",
    entidadTipo: "solicitudContratacion",
    entidadId: "CONT-26-001",
    creadoEn: "2026-07-10T08:15:00.000Z",
  },
  {
    id: "NOTIF-003",
    usuarioId: "USR-RH-012",
    titulo: "Evaluación aprobada",
    mensaje: "La evaluación de desempeño S1-2026 de todos los empleados ha sido aprobada",
    categoria: "rrhh",
    prioridad: "baja",
    leida: true,
    creadoEn: "2026-07-09T16:45:00.000Z",
  },
  {
    id: "NOTIF-004",
    usuarioId: "USR-VRAF-001",
    titulo: "Aprobación requerida",
    mensaje: "La solicitud de contratación para Analista TI requiere su aprobación en etapa final",
    categoria: "rrhh",
    prioridad: "alta",
    leida: false,
    accionUrl: "/ws/rrhh/contratacion",
    entidadTipo: "solicitudContratacion",
    entidadId: "CONT-26-001",
    creadoEn: "2026-07-10T07:00:00.000Z",
  },
  {
    id: "NOTIF-005",
    usuarioId: "USR-VRAF-001",
    titulo: "Proceso en riesgo",
    mensaje: "El proceso 'Auditoría Financiera Q2 2026' está vencido y requiere atención inmediata",
    categoria: "proceso",
    prioridad: "alta",
    leida: false,
    accionUrl: "/ws/vraf/procesos",
    entidadTipo: "proceso",
    entidadId: "PROC-VRAF-26-002",
    creadoEn: "2026-07-10T06:00:00.000Z",
  },
];

export const mockFormularios: Formulario[] = [
  {
    id: "FORM-RH-001-v1",
    nombre: "Solicitud de Plaza",
    unidadId: "rrhh",
    version: "1.0",
    estado: "publicado",
    schema: {
      title: "Solicitud de Plaza",
      fields: [
        { id: "cargo", label: "Cargo solicitado", type: "text", required: true, placeholder: "Ej: Analista de Recursos Humanos" },
        { id: "justificacion", label: "Justificación de la plaza", type: "textarea", required: true, placeholder: "Describa la necesidad y justificación..." },
        { id: "tipoContrato", label: "Tipo de contrato", type: "select", required: true, options: [{ value: "indefinido", label: "Indefinido" }, { value: "plazo_fijo", label: "Plazo fijo" }, { value: "eventual", label: "Eventual" }] },
        { id: "salarioPropuesto", label: "Salario propuesto ($)", type: "number", required: true, min: 365 },
        { id: "fechaInicio", label: "Fecha de inicio estimada", type: "date" },
      ],
    },
    guardadoEnBiblioteca: true,
    autor: "USR-RH-012",
    fecha: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "FORM-RH-002-v1",
    nombre: "Resultados de Prueba Técnica",
    unidadId: "rrhh",
    version: "1.0",
    estado: "publicado",
    schema: {
      title: "Resultados de Prueba Técnica",
      fields: [
        { id: "candidato", label: "Nombre del candidato", type: "text", required: true },
        { id: "puntuacion", label: "Puntuación obtenida (0–100)", type: "number", required: true, min: 0, max: 100 },
        { id: "observaciones", label: "Observaciones del evaluador", type: "textarea", placeholder: "Fortalezas y debilidades observadas..." },
        { id: "apto", label: "¿Candidato apto para continuar?", type: "boolean", required: true },
      ],
    },
    guardadoEnBiblioteca: true,
    autor: "USR-RH-012",
    fecha: "2026-01-15T00:00:00.000Z",
  },
  {
    id: "FORM-RH-003-v1",
    nombre: "Acta de Entrevista",
    unidadId: "rrhh",
    version: "1.0",
    estado: "publicado",
    schema: {
      title: "Acta de Entrevista Panel",
      fields: [
        { id: "candidato", label: "Nombre del candidato", type: "text", required: true },
        { id: "fecha", label: "Fecha de entrevista", type: "date", required: true },
        { id: "competencias", label: "Evaluación de competencias (0–10)", type: "number", required: true, min: 0, max: 10 },
        { id: "experiencia", label: "Adecuación de la experiencia (0–10)", type: "number", required: true, min: 0, max: 10 },
        { id: "actitud", label: "Actitud y cultura organizacional (0–10)", type: "number", required: true, min: 0, max: 10 },
        { id: "observaciones", label: "Observaciones del panel", type: "textarea" },
        { id: "recomendacion", label: "Recomendación del panel", type: "select", required: true, options: [{ value: "contratar", label: "Contratar" }, { value: "lista_espera", label: "Lista de espera" }, { value: "no_seleccionado", label: "No seleccionado" }] },
      ],
    },
    guardadoEnBiblioteca: true,
    autor: "USR-RH-012",
    fecha: "2026-01-15T00:00:00.000Z",
  },
];
