/**
 * Datos simulados para el Procedimiento PRO-TH-001
 * Reclutamiento, Selección y Contratación — UPES
 *
 * 4 procesos en diferentes etapas, con candidatos y documentos de soporte.
 */

import type {
  ProcesoContratacion,
  CandidatoCV,
  RequisicionPersonal,
  InformeTecnicoSeleccion,
  InformeSeleccionFinal,
  CartaOferta,
  ExpedientePersonal,
  FichaEmpleado,
  FichaDocente,
  ContratoTrabajo,
  MatrizCompetencias,
} from '@/types/contratacion';

// ── Helpers ───────────────────────────────────────────────────────────────────

const COMPETENCIAS_ADMIN: MatrizCompetencias = {
  comprensionVerbalEscrita: true,
  seguimientoProcedimientos: true,
  interpretacionNormativas: true,
  manejoInformacion: true,
  capacidadSintesis: false,
  manejoPersonalGrupos: false,
  tomaDecisionesBajoPresion: true,
  poderPersonal: false,
  negociacionMediacion: false,
  delegacionEfectiva: false,
  facilidadPalabra: true,
  dominioPúblico: false,
  redaccionTecnica: true,
  asertividad: true,
  empatiaServicio: true,
  iniciativaProactividad: true,
  orientacionResultados: true,
  trabajoEquipo: true,
  adaptabilidadCambios: true,
  optimizacionTiempo: true,
  planificacionDidactica: false,
  disenoInstrumentos: false,
  metodologiasInvestigacion: false,
  actualizacionConstante: true,
  eticaProfesional: true,
  dominioOffice365: true,
  inteligenciaArtificial: false,
  baseDatos: false,
  ciberseguridad: false,
  manejoPlatformas: true,
};

const COMPETENCIAS_INVESTIGACION: MatrizCompetencias = {
  comprensionVerbalEscrita: true,
  seguimientoProcedimientos: true,
  interpretacionNormativas: true,
  manejoInformacion: true,
  capacidadSintesis: true,
  manejoPersonalGrupos: true,
  tomaDecisionesBajoPresion: true,
  poderPersonal: true,
  negociacionMediacion: true,
  delegacionEfectiva: true,
  facilidadPalabra: true,
  dominioPúblico: true,
  redaccionTecnica: true,
  asertividad: true,
  empatiaServicio: true,
  iniciativaProactividad: true,
  orientacionResultados: true,
  trabajoEquipo: true,
  adaptabilidadCambios: true,
  optimizacionTiempo: true,
  planificacionDidactica: true,
  disenoInstrumentos: true,
  metodologiasInvestigacion: true,
  actualizacionConstante: true,
  eticaProfesional: true,
  dominioOffice365: true,
  inteligenciaArtificial: true,
  baseDatos: true,
  ciberseguridad: false,
  manejoPlatformas: true,
};

const COMPETENCIAS_IT: MatrizCompetencias = {
  comprensionVerbalEscrita: true,
  seguimientoProcedimientos: true,
  interpretacionNormativas: false,
  manejoInformacion: true,
  capacidadSintesis: true,
  manejoPersonalGrupos: false,
  tomaDecisionesBajoPresion: true,
  poderPersonal: false,
  negociacionMediacion: false,
  delegacionEfectiva: false,
  facilidadPalabra: true,
  dominioPúblico: false,
  redaccionTecnica: true,
  asertividad: true,
  empatiaServicio: true,
  iniciativaProactividad: true,
  orientacionResultados: true,
  trabajoEquipo: true,
  adaptabilidadCambios: true,
  optimizacionTiempo: true,
  planificacionDidactica: false,
  disenoInstrumentos: false,
  metodologiasInvestigacion: false,
  actualizacionConstante: true,
  eticaProfesional: true,
  dominioOffice365: true,
  inteligenciaArtificial: true,
  baseDatos: true,
  ciberseguridad: true,
  manejoPlatformas: true,
};

// ── PROCESO 1: publicacion_vacante ────────────────────────────────────────────
// Asistente Académico — FIET (Facultad de Ingeniería y Tecnología)

export const PROCESO_FIET_001: ProcesoContratacion = {
  id: 'PROC-RH-26-001',
  codigo: 'PROC-RH-26-001',
  tipoPuesto: 'plaza_existente',
  nombrePuesto: 'Asistente Académico',
  unidadFacultad: 'Facultad de Ingeniería y Tecnología (FIET)',
  jefeSolicitante: 'Ing. Mauricio Ernesto Villalobos',
  cargoSolicitante: 'Decano FIET',
  tipoContratacion: 'interino',
  motivoVacante: 'permiso_licencia',
  etapaActual: 'publicacion_vacante',
  pasoActual: 10,
  estrategiaReclutamiento: 'externa',
  prioridad: 'urgente',
  requisicionId: 'REQ-RH-26-001',
  candidatos: [],
  terna: [],
  opcionesOferta: [],
  historial: [
    {
      id: 'EVT-001-01',
      fecha: '2026-07-01T08:00:00Z',
      paso: 1,
      etapa: 'identificacion_necesidad',
      accion: 'Identificación de necesidad de cobertura de plaza vacante por permiso con goce de sueldo',
      responsable: 'Ing. Mauricio Ernesto Villalobos',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-001-02',
      fecha: '2026-07-02T09:00:00Z',
      paso: 2,
      etapa: 'identificacion_necesidad',
      accion: 'Verificación de disponibilidad presupuestaria con Vicerrectoría Administrativa',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
      notas: 'Partida presupuestaria 2100-003 disponible para el período julio-diciembre 2026.',
    },
    {
      id: 'EVT-001-03',
      fecha: '2026-07-03T10:00:00Z',
      paso: 8,
      etapa: 'requisicion',
      accion: 'Envío de Formulario de Requisición de Personal a RRHH',
      responsable: 'Ing. Mauricio Ernesto Villalobos',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-001-04',
      fecha: '2026-07-05T08:30:00Z',
      paso: 9,
      etapa: 'estrategia_reclutamiento',
      accion: 'Definición de estrategia de reclutamiento: convocatoria externa mediante portal institucional y redes sociales',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-001-05',
      fecha: '2026-07-07T08:00:00Z',
      paso: 10,
      etapa: 'publicacion_vacante',
      accion: 'Publicación de convocatoria en portal web institucional y redes sociales oficiales',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-001-06',
      fecha: '2026-07-08T09:00:00Z',
      paso: 11,
      etapa: 'publicacion_vacante',
      accion: 'Difusión en bolsas de empleo: OCC Mundial, LinkedIn, InfoJobs El Salvador',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
  ],
  createdAt: '2026-07-01T08:00:00Z',
  updatedAt: '2026-07-08T09:00:00Z',
};

export const REQUISICION_FIET_001: RequisicionPersonal = {
  id: 'REQ-RH-26-001',
  procesoId: 'PROC-RH-26-001',
  unidadFacultad: 'Facultad de Ingeniería y Tecnología (FIET)',
  nombreSolicitante: 'Ing. Mauricio Ernesto Villalobos',
  cargoSolicitante: 'Decano FIET',
  fechaSolicitud: '2026-07-03',
  tipoRequisicion: 'cobertura_vacante',
  tipoContratacion: 'interino',
  motivoVacante: 'permiso_licencia',
  nombrePuesto: 'Asistente Académico',
  areaDepartamento: 'Decanato FIET',
  ubicacionFisica: 'Edificio FIET, 2.° piso, oficina 201 — Sede Central UPES',
  horarioJornada: 'Lunes a viernes, 7:30 a.m. – 4:30 p.m.',
  escolaridadGradoAcademico: 'Licenciatura o Ingeniería en área afín (graduado). Se valorará especialización en gestión educativa.',
  dominioIdiomas: 'Español nativo. Inglés técnico intermedio deseable.',
  manejeSistemas: 'Office 365 (Word, Excel, Outlook, Teams). Sistema Académico Institucional SIUPE.',
  experienciaFunciones:
    'Mínimo 1 año en puestos administrativos o académicos en instituciones de educación superior. ' +
    'Funciones: apoyo a decanato en gestión académica, coordinación de horarios, atención a docentes y estudiantes, elaboración de informes.',
  competencias: COMPETENCIAS_ADMIN,
  otrasHabilidades: 'Manejo de archivo físico y digital. Redacción de actas y memorandos. Discreción y confidencialidad institucional.',
  firmaSolicita: 'Ing. Mauricio Ernesto Villalobos',
  firmaAutoriza: 'Dr. José Antonio Vásquez — Rector',
  fechaRecibidoRRHH: '2026-07-03',
  periodoDesde: '2026-08-01',
  periodoHasta: '2026-12-31',
  notaRRHH: 'Cobertura por permiso con goce de sueldo autorizado mediante resolución R-026-2026.',
  estado: 'aprobada',
  createdAt: '2026-07-03T10:00:00Z',
  updatedAt: '2026-07-05T08:30:00Z',
};

// ── PROCESO 2: conformacion_terna ─────────────────────────────────────────────
// Coordinador de Investigación — Rectoría

export const CANDIDATOS_RECTORIA: CandidatoCV[] = [
  {
    id: 'CAND-RH-26-002-A',
    procesoId: 'PROC-RH-26-002',
    nombre: 'Jorge Alejandro',
    apellido: 'Montes Gutiérrez',
    email: 'jmontes.candidate@gmail.com',
    telefono: '7812-3456',
    titulo: 'MSc. en Gestión de la Investigación Científica — Universidad de Costa Rica',
    experienciaAnios: 7,
    cvUrl: 'https://drive.google.com/file/cand-002-A',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 82,
    notaPruebaTecnica: 88,
    notaPruebaConductual: 79,
    notaEntrevistaRRHH: 85,
    promedioGeneral: 83.5,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-06-25T10:00:00Z',
  },
  {
    id: 'CAND-RH-26-002-B',
    procesoId: 'PROC-RH-26-002',
    nombre: 'Karla Beatriz',
    apellido: 'Salinas Portillo',
    email: 'ksalinas.candidate@outlook.com',
    telefono: '7654-9012',
    titulo: 'Doctora en Ciencias de la Educación — Universidad de El Salvador',
    experienciaAnios: 10,
    cvUrl: 'https://drive.google.com/file/cand-002-B',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 90,
    notaPruebaTecnica: 92,
    notaPruebaConductual: 88,
    notaEntrevistaRRHH: 91,
    promedioGeneral: 90.25,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-06-26T09:30:00Z',
  },
  {
    id: 'CAND-RH-26-002-C',
    procesoId: 'PROC-RH-26-002',
    nombre: 'Ricardo Antonio',
    apellido: 'Fuentes Aguilar',
    email: 'rfuentes.cv@gmail.com',
    telefono: '7321-5678',
    titulo: 'MSc. en Políticas Públicas de Ciencia y Tecnología — FLACSO El Salvador',
    experienciaAnios: 5,
    cvUrl: 'https://drive.google.com/file/cand-002-C',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 75,
    notaPruebaTecnica: 78,
    notaPruebaConductual: 80,
    notaEntrevistaRRHH: 77,
    promedioGeneral: 77.5,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-06-27T11:00:00Z',
  },
  {
    id: 'CAND-RH-26-002-D',
    procesoId: 'PROC-RH-26-002',
    nombre: 'Ana Lorena',
    apellido: 'Pérez Mejía',
    email: 'aperez.ml@yahoo.com',
    telefono: '7901-2345',
    titulo: 'Licenciada en Administración de Empresas — ESEN',
    experienciaAnios: 3,
    cumplePerfilCV: false,
    enTerna: false,
    seleccionado: false,
    rechazado: true,
    motivoRechazo: 'Perfil académico no corresponde al área de investigación científica requerida.',
    createdAt: '2026-06-28T14:00:00Z',
  },
];

export const PROCESO_RECTORIA_002: ProcesoContratacion = {
  id: 'PROC-RH-26-002',
  codigo: 'PROC-RH-26-002',
  tipoPuesto: 'nueva_plaza',
  nombrePuesto: 'Coordinador de Investigación',
  unidadFacultad: 'Rectoría — Unidad de Investigación y Transferencia Tecnológica',
  jefeSolicitante: 'Dr. José Antonio Vásquez',
  cargoSolicitante: 'Rector',
  tipoContratacion: 'permanente',
  etapaActual: 'conformacion_terna',
  pasoActual: 16,
  estrategiaReclutamiento: 'externa',
  prioridad: 'urgente',
  requisicionId: 'REQ-RH-26-002',
  informeTecnicoId: undefined,
  candidatos: CANDIDATOS_RECTORIA,
  terna: ['CAND-RH-26-002-A', 'CAND-RH-26-002-B', 'CAND-RH-26-002-C'],
  opcionesOferta: [],
  historial: [
    {
      id: 'EVT-002-01',
      fecha: '2026-06-10T08:00:00Z',
      paso: 1,
      etapa: 'identificacion_necesidad',
      accion: 'Identificación de nueva necesidad: creación de plaza para Coordinador de Investigación en el marco del Plan Estratégico 2026-2030',
      responsable: 'Dr. José Antonio Vásquez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-002-02',
      fecha: '2026-06-12T09:00:00Z',
      paso: 8,
      etapa: 'requisicion',
      accion: 'Aprobación de Formulario de Requisición de Personal — nueva plaza autorizada por Junta Directiva',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-002-03',
      fecha: '2026-06-15T08:00:00Z',
      paso: 9,
      etapa: 'estrategia_reclutamiento',
      accion: 'Estrategia de reclutamiento externo: convocatoria abierta en portales académicos nacionales e internacionales',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-002-04',
      fecha: '2026-06-17T09:00:00Z',
      paso: 10,
      etapa: 'publicacion_vacante',
      accion: 'Publicación de convocatoria en portal institucional, ANUIES y Red Salvadoreña de Investigadores',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-002-05',
      fecha: '2026-06-30T16:00:00Z',
      paso: 12,
      etapa: 'recepcion_cv',
      accion: 'Cierre de recepción de hojas de vida. Total recibidas: 4. Cumplen perfil: 3.',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-002-06',
      fecha: '2026-07-02T08:00:00Z',
      paso: 13,
      etapa: 'entrevista_preliminar',
      accion: 'Entrevistas preliminares realizadas a los 3 candidatos que cumplen perfil',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-002-07',
      fecha: '2026-07-05T08:00:00Z',
      paso: 14,
      etapa: 'pruebas',
      accion: 'Aplicación de prueba técnica de conocimientos en gestión de investigación y prueba de personalidad (16PF)',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-002-08',
      fecha: '2026-07-08T08:00:00Z',
      paso: 15,
      etapa: 'entrevista_rrhh',
      accion: 'Entrevistas por competencias realizadas por Jefe de RRHH a los 3 candidatos preseleccionados',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-002-09',
      fecha: '2026-07-10T10:00:00Z',
      paso: 16,
      etapa: 'conformacion_terna',
      accion: 'Conformación de terna: Montes Gutiérrez (83.5), Salinas Portillo (90.25), Fuentes Aguilar (77.5)',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
  ],
  createdAt: '2026-06-10T08:00:00Z',
  updatedAt: '2026-07-10T10:00:00Z',
};

export const INFORME_TECNICO_RECTORIA: InformeTecnicoSeleccion = {
  id: 'INF-TEC-RH-26-002',
  procesoId: 'PROC-RH-26-002',
  cargo: 'Coordinador de Investigación',
  unidadFacultad: 'Rectoría — Unidad de Investigación y Transferencia Tecnológica',
  antecedentes:
    'En el marco del Plan Estratégico Institucional 2026-2030, la Rectoría de la Universidad Politécnica de El Salvador identificó la necesidad de crear la plaza de Coordinador de Investigación para fortalecer la producción científica y la transferencia tecnológica. La plaza fue debidamente requisicionada y aprobada mediante acuerdo de Junta Directiva N.° JD-026-2026.',
  objetivoCargo:
    'Planificar, coordinar y evaluar los programas y proyectos de investigación científica de la institución, promoviendo la vinculación con el sector productivo y la comunidad académica nacional e internacional.',
  terna: ['MSc. Jorge Alejandro Montes Gutiérrez', 'Dra. Karla Beatriz Salinas Portillo', 'MSc. Ricardo Antonio Fuentes Aguilar'],
  evaluaciones: [
    {
      nombre: 'MSc. Jorge Alejandro Montes Gutiérrez',
      sintesisEstrategica: 'Profesional con sólida experiencia en gestión de proyectos de investigación en educación superior, con participación en congresos internacionales y publicaciones en revistas indexadas.',
      formacionAcademica: 'Maestría en Gestión de la Investigación Científica, Universidad de Costa Rica (2019). Licenciatura en Ingeniería Industrial, UTEC (2015).',
      experienciaHabilidades: '7 años coordinando unidades de investigación en instituciones de educación superior. Dominio de plataformas de gestión de investigación y bases de datos científicas.',
      valoracionTecnica: 'Competente. Demuestra conocimiento práctico sólido con enfoque en resultados medibles.',
    },
    {
      nombre: 'Dra. Karla Beatriz Salinas Portillo',
      sintesisEstrategica: 'Doctora con amplia trayectoria en investigación educativa y dirección de proyectos interinstitucionales, con red de contactos académicos internacionales consolidada.',
      formacionAcademica: 'Doctorado en Ciencias de la Educación, Universidad de El Salvador (2021). Maestría en Pedagogía Universitaria, ESEN (2016). Licenciatura en Ciencias de la Educación, UES (2012).',
      experienciaHabilidades: '10 años en roles de investigación y coordinación académica. Publicaciones en revistas Q1 y Q2. Experiencia en gestión de fondos concursables CONACYT.',
      valoracionTecnica: 'Altamente competente. Perfil que supera los requisitos mínimos del cargo con visión estratégica institucional.',
    },
    {
      nombre: 'MSc. Ricardo Antonio Fuentes Aguilar',
      sintesisEstrategica: 'Especialista en políticas de ciencia y tecnología con experiencia en organismos gubernamentales, orientado al diseño de marcos normativos para la investigación.',
      formacionAcademica: 'Maestría en Políticas Públicas de Ciencia y Tecnología, FLACSO El Salvador (2022). Licenciatura en Ciencias Jurídicas, UES (2018).',
      experienciaHabilidades: '5 años en análisis de políticas públicas de CyT. Limitada experiencia en gestión directa de proyectos de investigación en IES.',
      valoracionTecnica: 'Competente con áreas de mejora. Perfil más orientado a política que a gestión operativa de investigación.',
    },
  ],
  matrizComparativa: [
    { criterio: 'Formación académica (posgrado área afín)', candidato1: '9/10', candidato2: '10/10', candidato3: '7/10' },
    { criterio: 'Experiencia en gestión de investigación (años)', candidato1: '8/10', candidato2: '10/10', candidato3: '6/10' },
    { criterio: 'Publicaciones científicas indexadas', candidato1: '7/10', candidato2: '10/10', candidato3: '5/10' },
    { criterio: 'Conocimiento normativa CONACYT y fondos concursables', candidato1: '8/10', candidato2: '9/10', candidato3: '8/10' },
    { criterio: 'Liderazgo y gestión de equipos', candidato1: '8/10', candidato2: '9/10', candidato3: '7/10' },
    { criterio: 'Dominio de plataformas de investigación', candidato1: '9/10', candidato2: '9/10', candidato3: '6/10' },
  ],
  conclusion:
    'Los tres candidatos cumplen con los requisitos de la plaza. Sin embargo, existe diferencia significativa en el nivel de experiencia y producción científica. La Dra. Salinas Portillo destaca por su formación doctoral, mayor experiencia y red de contactos académicos que beneficiarían directamente a la UPES.',
  recomendacion:
    'Se recomienda contratar a la Dra. Karla Beatriz Salinas Portillo como primera opción para el cargo de Coordinador de Investigación, seguida del MSc. Montes Gutiérrez como segunda opción y el MSc. Fuentes Aguilar como tercera opción.',
  candidatoRecomendado: 'Dra. Karla Beatriz Salinas Portillo',
  firmaJefeRRHH: 'Licda. María José Hernández',
  fechaInforme: '2026-07-10',
  estado: 'borrador',
  createdAt: '2026-07-10T11:00:00Z',
};

// ── PROCESO 3: carta_oferta ───────────────────────────────────────────────────
// Técnico de Soporte IT — Dirección de Tecnología y Administración Informática (DTAI)

export const CANDIDATOS_DTAI: CandidatoCV[] = [
  {
    id: 'CAND-RH-26-003-A',
    procesoId: 'PROC-RH-26-003',
    nombre: 'Nelson Eduardo',
    apellido: 'Hernández Rivas',
    email: 'nehernandez.cv@gmail.com',
    telefono: '7456-7890',
    titulo: 'Ingeniero en Sistemas Informáticos — Universidad Don Bosco',
    experienciaAnios: 4,
    cvUrl: 'https://drive.google.com/file/cand-003-A',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 80,
    notaPruebaTecnica: 85,
    notaPruebaConductual: 78,
    notaEntrevistaRRHH: 82,
    notaEntrevistaFinal: 84,
    promedioGeneral: 81.8,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-07-01T09:00:00Z',
  },
  {
    id: 'CAND-RH-26-003-B',
    procesoId: 'PROC-RH-26-003',
    nombre: 'Diana Marcela',
    apellido: 'Guardado López',
    email: 'dguardado.tech@outlook.com',
    telefono: '7234-5678',
    titulo: 'Técnica en Soporte de Redes y Telecomunicaciones — ITCA-FEPADE',
    experienciaAnios: 6,
    cvUrl: 'https://drive.google.com/file/cand-003-B',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 88,
    notaPruebaTecnica: 91,
    notaPruebaConductual: 85,
    notaEntrevistaRRHH: 89,
    notaEntrevistaFinal: 90,
    promedioGeneral: 88.6,
    enTerna: true,
    seleccionado: true,
    rechazado: false,
    createdAt: '2026-07-01T10:00:00Z',
  },
  {
    id: 'CAND-RH-26-003-C',
    procesoId: 'PROC-RH-26-003',
    nombre: 'Cristian Roberto',
    apellido: 'Amaya Sánchez',
    email: 'cramaya.it@gmail.com',
    telefono: '7890-1234',
    titulo: 'Ingeniero en Telecomunicaciones — Universidad Centroamericana José Simeón Cañas',
    experienciaAnios: 3,
    cvUrl: 'https://drive.google.com/file/cand-003-C',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 72,
    notaPruebaTecnica: 76,
    notaPruebaConductual: 74,
    notaEntrevistaRRHH: 73,
    notaEntrevistaFinal: 74,
    promedioGeneral: 73.8,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-07-01T11:00:00Z',
  },
];

export const PROCESO_DTAI_003: ProcesoContratacion = {
  id: 'PROC-RH-26-003',
  codigo: 'PROC-RH-26-003',
  tipoPuesto: 'plaza_existente',
  nombrePuesto: 'Técnico de Soporte IT',
  unidadFacultad: 'Dirección de Tecnología y Administración Informática (DTAI)',
  jefeSolicitante: 'Ing. Roberto Morales Aguilar',
  cargoSolicitante: 'Director DTAI',
  tipoContratacion: 'permanente',
  motivoVacante: 'retiro_voluntario',
  etapaActual: 'carta_oferta',
  pasoActual: 21,
  estrategiaReclutamiento: 'externa',
  prioridad: 'urgente',
  requisicionId: 'REQ-RH-26-003',
  informeTecnicoId: 'INF-TEC-RH-26-003',
  informeFinalId: 'INF-FIN-RH-26-003',
  cartaOfertaId: 'CARTA-RH-26-003',
  candidatoSeleccionadoId: 'CAND-RH-26-003-B',
  candidatos: CANDIDATOS_DTAI,
  terna: ['CAND-RH-26-003-A', 'CAND-RH-26-003-B', 'CAND-RH-26-003-C'],
  opcionesOferta: ['CAND-RH-26-003-B', 'CAND-RH-26-003-A', 'CAND-RH-26-003-C'],
  historial: [
    {
      id: 'EVT-003-01',
      fecha: '2026-06-20T08:00:00Z',
      paso: 1,
      etapa: 'identificacion_necesidad',
      accion: 'Identificación de vacante por retiro voluntario del técnico en funciones',
      responsable: 'Ing. Roberto Morales Aguilar',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-02',
      fecha: '2026-06-22T09:00:00Z',
      paso: 8,
      etapa: 'requisicion',
      accion: 'Formulario de Requisición de Personal enviado y aprobado',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-003-03',
      fecha: '2026-06-24T10:00:00Z',
      paso: 9,
      etapa: 'estrategia_reclutamiento',
      accion: 'Estrategia de reclutamiento externo aprobada',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-003-04',
      fecha: '2026-06-25T08:00:00Z',
      paso: 10,
      etapa: 'publicacion_vacante',
      accion: 'Publicación de convocatoria en portal institucional y plataformas especializadas TI',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-05',
      fecha: '2026-07-04T16:00:00Z',
      paso: 12,
      etapa: 'recepcion_cv',
      accion: 'Cierre de recepción de hojas de vida. Total recibidas: 6. Cumplen perfil: 3.',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-06',
      fecha: '2026-07-06T08:00:00Z',
      paso: 13,
      etapa: 'entrevista_preliminar',
      accion: 'Entrevistas preliminares realizadas a 3 candidatos preseleccionados',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-003-07',
      fecha: '2026-07-07T08:00:00Z',
      paso: 14,
      etapa: 'pruebas',
      accion: 'Prueba técnica de conocimientos IT (redes, soporte, sistemas operativos) y prueba de personalidad',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-08',
      fecha: '2026-07-08T08:00:00Z',
      paso: 15,
      etapa: 'entrevista_rrhh',
      accion: 'Entrevistas por competencias con Jefe de RRHH',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-003-09',
      fecha: '2026-07-09T09:00:00Z',
      paso: 16,
      etapa: 'conformacion_terna',
      accion: 'Conformación de terna preseleccionada para entrevista final',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-10',
      fecha: '2026-07-10T10:00:00Z',
      paso: 17,
      etapa: 'entrevista_final',
      accion: 'Entrevistas finales con Director DTAI y Jefe de RRHH realizadas a los 3 candidatos de la terna',
      responsable: 'Ing. Roberto Morales Aguilar',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-11',
      fecha: '2026-07-11T09:00:00Z',
      paso: 18,
      etapa: 'informe_seleccion',
      accion: 'Emisión de Informe Técnico de Selección y de Informe de Selección Final',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-003-12',
      fecha: '2026-07-12T10:00:00Z',
      paso: 19,
      etapa: 'validacion_rector',
      accion: 'Presentación de informe y terna al Rector para validación',
      responsable: 'Dr. José Antonio Vásquez',
      resultado: 'aprobado',
      notas: 'El Rector aprobó la selección de la candidata Guardado López como primera opción.',
    },
    {
      id: 'EVT-003-13',
      fecha: '2026-07-14T08:00:00Z',
      paso: 21,
      etapa: 'carta_oferta',
      accion: 'Emisión de Carta Oferta a candidata seleccionada Diana Marcela Guardado López',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
  ],
  createdAt: '2026-06-20T08:00:00Z',
  updatedAt: '2026-07-14T08:00:00Z',
};

export const CARTA_OFERTA_DTAI: CartaOferta = {
  id: 'CARTA-RH-26-003',
  procesoId: 'PROC-RH-26-003',
  candidatoId: 'CAND-RH-26-003-B',
  opcion: 1,
  ciudad: 'San Salvador',
  dia: 14,
  mes: 'julio',
  anio: 2026,
  profesionCandidato: 'Técnica en Soporte de Redes y Telecomunicaciones',
  nombreCandidato: 'Diana Marcela Guardado López',
  cargoOfrecido: 'Técnico de Soporte IT',
  diaInicio: 1,
  mesInicio: 'agosto',
  salarioMensual: 850.00,
  horario: 'Lunes a viernes, 8:00 a.m. – 5:00 p.m., con disponibilidad eventual en fines de semana',
  indemnizacion: true,
  vacaciones: true,
  afp: true,
  isss: true,
  aguinaldo: true,
  formacionContinua: true,
  seguroVida: false,
  desarrolloProfesional: true,
  estado: 'emitida',
  createdAt: '2026-07-14T08:00:00Z',
};

export const INFORME_FINAL_DTAI: InformeSeleccionFinal = {
  id: 'INF-FIN-RH-26-003',
  procesoId: 'PROC-RH-26-003',
  fechaInforme: '2026-07-11',
  unidadFacultad: 'Dirección de Tecnología y Administración Informática (DTAI)',
  puestoCubrir: 'Técnico de Soporte IT',
  terna: [
    { nombre: 'Diana Marcela Guardado López', puntajePromedio: 88.6, resultadoGlobal: 'Excelente' },
    { nombre: 'Nelson Eduardo Hernández Rivas', puntajePromedio: 81.8, resultadoGlobal: 'Muy Bueno' },
    { nombre: 'Cristian Roberto Amaya Sánchez', puntajePromedio: 73.8, resultadoGlobal: 'Bueno' },
  ],
  competenciaTecnica:
    'La señorita Guardado López demostró dominio técnico superior en redes LAN/WAN, soporte a usuarios, gestión de Active Directory y administración de sistemas operativos Windows Server. Obtuvo la puntuación más alta en la prueba técnica (91/100).',
  alineacionInstitucional:
    'Los tres candidatos mostraron conocimiento de la misión y valores institucionales. La candidata seleccionada destacó por su experiencia previa en entornos educativos y comprensión de las particularidades del soporte tecnológico en instituciones de educación superior.',
  habilidadesBlandas:
    'Guardado López sobresalió en comunicación asertiva, orientación al servicio y trabajo en equipo, competencias críticas para el cargo que requiere atención permanente a docentes, estudiantes y personal administrativo.',
  candidatoSeleccionado: 'Diana Marcela Guardado López',
  justificacion:
    'Con base en la evaluación integral (entrevistas, pruebas técnicas y conductuales, y entrevista final), la señorita Guardado López es la candidata que mejor cumple el perfil requerido para el cargo de Técnico de Soporte IT, superando a los demás integrantes de la terna en todas las dimensiones evaluadas.',
  firmaJefeInmediato: 'Ing. Roberto Morales Aguilar',
  nombreJefeInmediato: 'Director DTAI',
  vistoBuenoRRHH: 'Licda. María José Hernández — Jefa de Recursos Humanos',
  estado: 'emitido',
  createdAt: '2026-07-11T09:00:00Z',
};

// ── PROCESO 4: completado ─────────────────────────────────────────────────────
// Docente Hora Clase — Facultad de Ciencias Empresariales y Administración (FCEA)

export const CANDIDATOS_FCEA: CandidatoCV[] = [
  {
    id: 'CAND-RH-26-004-A',
    procesoId: 'PROC-RH-26-004',
    nombre: 'Claudia Patricia',
    apellido: 'Ramos Orellana',
    email: 'cramos.docente@gmail.com',
    telefono: '7567-8901',
    titulo: 'MSc. en Administración de Empresas — Universidad Francisco Gavidia',
    experienciaAnios: 8,
    cvUrl: 'https://drive.google.com/file/cand-004-A',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 85,
    notaPruebaTecnica: 88,
    notaPruebaConductual: 83,
    notaEntrevistaRRHH: 86,
    notaEntrevistaFinal: 87,
    promedioGeneral: 85.8,
    enTerna: true,
    seleccionado: true,
    rechazado: false,
    createdAt: '2026-05-15T09:00:00Z',
  },
  {
    id: 'CAND-RH-26-004-B',
    procesoId: 'PROC-RH-26-004',
    nombre: 'Miguel Ángel',
    apellido: 'Portillo Castellanos',
    email: 'mportillo.prof@outlook.com',
    telefono: '7123-4567',
    titulo: 'Licenciado en Contaduría Pública — Universidad de El Salvador',
    experienciaAnios: 5,
    cvUrl: 'https://drive.google.com/file/cand-004-B',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 78,
    notaPruebaTecnica: 80,
    notaPruebaConductual: 79,
    notaEntrevistaRRHH: 78,
    notaEntrevistaFinal: 79,
    promedioGeneral: 78.8,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-05-16T10:00:00Z',
  },
  {
    id: 'CAND-RH-26-004-C',
    procesoId: 'PROC-RH-26-004',
    nombre: 'Sonia Elizabeth',
    apellido: 'Díaz Molina',
    email: 'sdiaz.mba@gmail.com',
    telefono: '7890-2345',
    titulo: 'MBA — ESEN (Escuela Superior de Economía y Negocios)',
    experienciaAnios: 12,
    cvUrl: 'https://drive.google.com/file/cand-004-C',
    cumplePerfilCV: true,
    notaEntrevistaPrelimininar: 80,
    notaPruebaTecnica: 82,
    notaPruebaConductual: 84,
    notaEntrevistaRRHH: 81,
    notaEntrevistaFinal: 82,
    promedioGeneral: 81.8,
    enTerna: true,
    seleccionado: false,
    rechazado: false,
    createdAt: '2026-05-17T11:00:00Z',
  },
];

export const PROCESO_FCEA_004: ProcesoContratacion = {
  id: 'PROC-RH-26-004',
  codigo: 'PROC-RH-26-004',
  tipoPuesto: 'plaza_existente',
  nombrePuesto: 'Docente Hora Clase — Administración de Empresas',
  unidadFacultad: 'Facultad de Ciencias Empresariales y Administración (FCEA)',
  jefeSolicitante: 'Licda. Carmen Elena Molina',
  cargoSolicitante: 'Decana FCEA',
  tipoContratacion: 'eventual',
  motivoVacante: 'terminacion_contrato',
  etapaActual: 'completado',
  pasoActual: 27,
  estrategiaReclutamiento: 'externa',
  prioridad: 'normal',
  requisicionId: 'REQ-RH-26-004',
  informeTecnicoId: 'INF-TEC-RH-26-004',
  informeFinalId: 'INF-FIN-RH-26-004',
  cartaOfertaId: 'CARTA-RH-26-004',
  expedienteId: 'EXP-RH-26-004',
  contratoId: 'CONT-RH-26-004',
  fichaEmpleadoId: 'FICHA-DOC-RH-26-004',
  candidatoSeleccionadoId: 'CAND-RH-26-004-A',
  candidatos: CANDIDATOS_FCEA,
  terna: ['CAND-RH-26-004-A', 'CAND-RH-26-004-B', 'CAND-RH-26-004-C'],
  opcionesOferta: ['CAND-RH-26-004-A', 'CAND-RH-26-004-C', 'CAND-RH-26-004-B'],
  ofertaAceptadaPor: 'CAND-RH-26-004-A',
  historial: [
    {
      id: 'EVT-004-01',
      fecha: '2026-05-05T08:00:00Z',
      paso: 1,
      etapa: 'identificacion_necesidad',
      accion: 'Identificación de vacante por vencimiento de contrato de docente hora clase ciclo I-2026',
      responsable: 'Licda. Carmen Elena Molina',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-02',
      fecha: '2026-05-07T09:00:00Z',
      paso: 8,
      etapa: 'requisicion',
      accion: 'Requisición de Personal aprobada por RRHH',
      responsable: 'Licda. María José Hernández',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-004-03',
      fecha: '2026-05-10T08:00:00Z',
      paso: 12,
      etapa: 'recepcion_cv',
      accion: 'Recepción de hojas de vida. Total recibidas: 5. Cumplen perfil: 3.',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-04',
      fecha: '2026-05-20T08:00:00Z',
      paso: 17,
      etapa: 'entrevista_final',
      accion: 'Entrevistas finales con Decana FCEA y Jefe de RRHH',
      responsable: 'Licda. Carmen Elena Molina',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-05',
      fecha: '2026-05-22T09:00:00Z',
      paso: 18,
      etapa: 'informe_seleccion',
      accion: 'Informe de selección emitido. Candidata recomendada: Ramos Orellana.',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-06',
      fecha: '2026-05-24T10:00:00Z',
      paso: 19,
      etapa: 'validacion_rector',
      accion: 'Validación de selección por Rector — aprobada',
      responsable: 'Dr. José Antonio Vásquez',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-004-07',
      fecha: '2026-05-26T08:00:00Z',
      paso: 21,
      etapa: 'carta_oferta',
      accion: 'Carta Oferta emitida y entregada a candidata seleccionada',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-08',
      fecha: '2026-05-27T14:00:00Z',
      paso: 22,
      etapa: 'carta_oferta',
      accion: 'Carta Oferta aceptada por la candidata Claudia Patricia Ramos Orellana',
      responsable: 'Claudia Patricia Ramos Orellana',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-004-09',
      fecha: '2026-05-28T08:00:00Z',
      paso: 23,
      etapa: 'creacion_expediente',
      accion: 'Creación y revisión de expediente de personal. Estado: completo.',
      responsable: 'Ing. Carlos Ramírez',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-10',
      fecha: '2026-05-29T09:00:00Z',
      paso: 24,
      etapa: 'elaboracion_contrato',
      accion: 'Elaboración de Contrato de Trabajo por servicios eventuales ciclo II-2026',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-11',
      fecha: '2026-05-30T10:00:00Z',
      paso: 25,
      etapa: 'firma_contrato',
      accion: 'Firma de contrato por empleada y Rector. Contrato vigente.',
      responsable: 'Dr. José Antonio Vásquez',
      resultado: 'aprobado',
    },
    {
      id: 'EVT-004-12',
      fecha: '2026-06-01T08:00:00Z',
      paso: 26,
      etapa: 'comunicacion',
      accion: 'Comunicación de nueva contratación a Decanato FCEA, TI y Administración Académica',
      responsable: 'Licda. María José Hernández',
      resultado: 'ejecutado',
    },
    {
      id: 'EVT-004-13',
      fecha: '2026-06-02T08:00:00Z',
      paso: 27,
      etapa: 'vinculacion_induccion',
      accion: 'Inducción institucional completada. Accesos a SIUPE y Office 365 habilitados. Proceso finalizado.',
      responsable: 'Licda. Ana Beatriz Flores',
      resultado: 'ejecutado',
    },
  ],
  createdAt: '2026-05-05T08:00:00Z',
  updatedAt: '2026-06-02T09:00:00Z',
};

export const CONTRATO_FCEA: ContratoTrabajo = {
  id: 'CONT-RH-26-004',
  procesoId: 'PROC-RH-26-004',
  nombreEmpleado: 'Claudia Patricia Ramos Orellana',
  profesionSegunDUI: 'Licenciada en Administración de Empresas',
  estadoCivil: 'soltera',
  distrito: 'San Salvador',
  municipio: 'San Salvador',
  departamento: 'San Salvador',
  duiParaContrato: '04521876-3',
  cargo: 'Docente Hora Clase — Administración de Empresas',
  salarioEnLetras: 'ochocientos dólares exactos',
  salario: 800.00,
  personasQueDependen: 'ninguna',
  fechaInicioContrato: 'uno de junio',
  fechaFinContrato: 'treinta y uno de diciembre del año dos mil veintiséis',
  anioContrato: 2026,
  fechaElaboracion: '2026-05-29',
  firmadoPorEmpleado: true,
  firmadoPorRector: true,
  fechaFirmaEmpleado: '2026-05-30',
  fechaFirmaRector: '2026-05-30',
  estado: 'vigente',
  createdAt: '2026-05-29T09:00:00Z',
};

export const EXPEDIENTE_FCEA: ExpedientePersonal = {
  id: 'EXP-RH-26-004',
  procesoId: 'PROC-RH-26-004',
  nombreCompleto: 'Claudia Patricia Ramos Orellana',
  numeroEmpleado: 'EMP-26-048',
  cargo: 'Docente Hora Clase',
  unidadDepartamento: 'Facultad de Ciencias Empresariales y Administración (FCEA)',
  tipoContratacion: 'eventual',
  fechaIngreso: '2026-06-01',
  responsableRevision: 'Ing. Carlos Ramírez',
  fechaRevision: '2026-05-28',
  documentosPersonales: [
    { numero: 1, documento: 'Hoja de Vida / Currículum Vitae', presenta: true, vigente: true },
    { numero: 2, documento: 'Fotocopia DUI vigente', presenta: true, vigente: true },
    { numero: 3, documento: 'Fotocopia NIT', presenta: true, vigente: true },
    { numero: 4, documento: 'Fotocopia de pasaporte (si aplica)', presenta: false, vigente: null },
    { numero: 5, documento: '2 fotografías tamaño cédula recientes', presenta: true, vigente: true },
    { numero: 6, documento: 'Partida de nacimiento original o certificada', presenta: true, vigente: true },
    { numero: 7, documento: 'Partida de matrimonio o acta de divorcio (si aplica)', presenta: false, vigente: null },
    { numero: 8, documento: 'Comprobante de NUP (AFP)', presenta: true, vigente: true },
    { numero: 9, documento: 'Comprobante de número ISSS', presenta: true, vigente: true },
    { numero: 10, documento: 'Constancia de antecedentes penales vigente', presenta: true, vigente: true },
  ],
  documentosAcademicos: [
    { numero: 1, documento: 'Fotocopia de título universitario o técnico', presenta: true, vigente: true },
    { numero: 2, documento: 'Certificado de notas universitario', presenta: true, vigente: true },
    { numero: 3, documento: 'Constancia de graduación (si el título está en trámite)', presenta: false, vigente: null },
    { numero: 4, documento: 'Diplomas de postgrado, cursos o certificaciones', presenta: true, vigente: true },
    { numero: 5, documento: 'Autorización de ejercicio profesional (si aplica)', presenta: false, vigente: null },
  ],
  documentosLaborales: [
    { numero: 1, documento: 'Cartas de referencia laboral (mínimo 2)', presenta: true, vigente: true },
    { numero: 2, documento: 'Constancias de trabajo anterior', presenta: true, vigente: true },
    { numero: 3, documento: 'Hoja de servicios del ISSS', presenta: true, vigente: true },
    { numero: 4, documento: 'Carta de renuncia o finiquito empleador anterior', presenta: true, vigente: true },
    { numero: 5, documento: 'Contrato de trabajo UPES firmado', presenta: true, vigente: true },
    { numero: 6, documento: 'Acta de entrega de lineamientos institucionales', presenta: true, vigente: true },
    { numero: 7, documento: 'Formulario de datos bancarios (depósito de salario)', presenta: true, vigente: true },
    { numero: 8, documento: 'Declaración jurada de no tener conflicto de interés', presenta: true, vigente: true },
    { numero: 9, documento: 'Ficha de Empleado firmada', presenta: true, vigente: true },
    { numero: 10, documento: 'Carta de aceptación de Carta Oferta', presenta: true, vigente: true },
  ],
  documentosMedicos: [
    { numero: 1, documento: 'Certificado médico de buena salud', presenta: true, vigente: true },
    { numero: 2, documento: 'Exámenes de laboratorio básicos', presenta: true, vigente: true },
    { numero: 3, documento: 'Declaración de discapacidad (si aplica)', presenta: false, vigente: null },
    { numero: 4, documento: 'Historial de vacunas (si aplica)', presenta: false, vigente: null },
  ],
  documentosAdministrativos: [
    { numero: 1, documento: 'Formulario de requisición de personal aprobado', presenta: true, vigente: true },
    { numero: 2, documento: 'Informe de selección firmado', presenta: true, vigente: true },
    { numero: 3, documento: 'Validación del Rector', presenta: true, vigente: true },
    { numero: 4, documento: 'Carta Oferta firmada por candidato', presenta: true, vigente: true },
  ],
  estadoExpediente: 'completo',
  documentosPendientes: 'Ninguno. Expediente completo al 100%.',
  accionesRequeridas: 'Ninguna acción requerida. Expediente listo para archivo definitivo.',
  firmaRRHH: 'Ing. Carlos Ramírez',
  firmaColaborador: 'Claudia Patricia Ramos Orellana',
  createdAt: '2026-05-28T08:00:00Z',
  updatedAt: '2026-05-30T10:00:00Z',
};

export const FICHA_DOCENTE_FCEA: FichaDocente = {
  id: 'FICHA-DOC-RH-26-004',
  procesoId: 'PROC-RH-26-004',
  nombre: 'Claudia Patricia Ramos Orellana',
  domicilio: 'Col. Escalón, 87 Av. Norte #231, San Salvador',
  telefono: '7567-8901',
  correoPersonal: 'cramos.docente@gmail.com',
  noDUI: '04521876-3',
  noNIT: '0614-150490-101-3',
  requeridoSujetoExcluido: false,
  lugarFechaNacimiento: 'San Salvador, El Salvador — 15 de abril de 1990',
  fechaIngreso: '2026-06-01',
  correoUPES: 'cramos@upes.edu.sv',
  cuentaDavivienda: 'DAV-00234567',
  numeroCuenta: '001234567890',
  nacionalidad: 'Salvadoreña',
  facultad: 'Facultad de Ciencias Empresariales y Administración (FCEA)',
  carrera: 'Administración de Empresas',
  nombreEmergencia: 'José Alfredo Ramos',
  parentescoEmergencia: 'Padre',
  telefonoEmergencia: '2222-3456',
  formacion: [
    {
      numero: 1,
      centroEstudios: 'Universidad Francisco Gavidia',
      gradoAcademico: 'Maestría en Administración de Empresas',
      temaGraduacion: 'Estrategias de Retención de Talento en PYMEs Salvadoreñas',
      anio: 2020,
      esPosgrado: true,
    },
    {
      numero: 2,
      centroEstudios: 'Universidad Centroamericana José Simeón Cañas',
      gradoAcademico: 'Licenciatura en Administración de Empresas',
      temaGraduacion: 'Modelo de Gestión por Competencias para el Sector Financiero',
      anio: 2014,
    },
  ],
  experienciaDocente: [
    { asignatura: 'Administración General', centroEstudios: 'Universidad Francisco Gavidia', anio: 2022 },
    { asignatura: 'Gestión del Talento Humano', centroEstudios: 'Instituto Tecnológico de El Salvador (ITES)', anio: 2021 },
    { asignatura: 'Liderazgo Organizacional', centroEstudios: 'Universidad Francisco Gavidia', anio: 2023 },
  ],
  experienciaLaboral: [
    { cargo: 'Gerente de Recursos Humanos', empresa: 'Grupo Agrisal S.A. de C.V.', desde: '2019-01', hasta: '2025-12' },
    { cargo: 'Analista de Capacitación', empresa: 'Banco Agrícola S.A.', desde: '2015-06', hasta: '2018-12' },
    { cargo: 'Asistente Administrativo', empresa: 'Cámara de Comercio e Industria de El Salvador', desde: '2013-01', hasta: '2015-05' },
  ],
  idiomas: [
    { idioma: 'Español', habla: true, lee: true, escribe: true },
    { idioma: 'Inglés', habla: true, lee: true, escribe: true },
  ],
  gremiales: ['Asociación Salvadoreña de Gestión Humana (AGESHU)'],
  referencias: [
    { nombre: 'Ing. Rafael Morales — Director de RRHH, Grupo Agrisal', telefono: '2100-5678' },
    { nombre: 'Licda. Sandra López — Directora de Capacitación, Banco Agrícola', telefono: '2234-5678' },
  ],
  createdAt: '2026-05-28T09:00:00Z',
};

// ── Índices de acceso ─────────────────────────────────────────────────────────

export const MOCK_PROCESOS: ProcesoContratacion[] = [
  PROCESO_FIET_001,
  PROCESO_RECTORIA_002,
  PROCESO_DTAI_003,
  PROCESO_FCEA_004,
];

export const MOCK_REQUISICIONES: RequisicionPersonal[] = [
  REQUISICION_FIET_001,
];

export const MOCK_INFORMES_TECNICOS: InformeTecnicoSeleccion[] = [
  INFORME_TECNICO_RECTORIA,
];

export const MOCK_INFORMES_FINALES: InformeSeleccionFinal[] = [
  INFORME_FINAL_DTAI,
];

export const MOCK_CARTAS_OFERTA: CartaOferta[] = [
  CARTA_OFERTA_DTAI,
];

export const MOCK_EXPEDIENTES: ExpedientePersonal[] = [
  EXPEDIENTE_FCEA,
];

export const MOCK_CONTRATOS: ContratoTrabajo[] = [
  CONTRATO_FCEA,
];

export const MOCK_FICHAS_DOCENTE: FichaDocente[] = [
  FICHA_DOCENTE_FCEA,
];

export const MOCK_CANDIDATOS: CandidatoCV[] = [
  ...CANDIDATOS_RECTORIA,
  ...CANDIDATOS_DTAI,
  ...CANDIDATOS_FCEA,
];

// Competencias exportadas para reutilización en tests y formularios
export { COMPETENCIAS_ADMIN, COMPETENCIAS_INVESTIGACION, COMPETENCIAS_IT };
