/**
 * Mock Blueprint Registry data for the Runtime Studio.
 * BP-RRHH-001 mirrors the real hiring blueprint from mock-workflow-data.ts.
 * Additional blueprints show draft/deprecated states for UI coverage.
 */
import type { BlueprintMetadata, InstanceSummary } from "@/types/studio";

export const mockBlueprintRegistry: BlueprintMetadata[] = [
  // ── Hiring Process (Published) ────────────────────────────────────────────
  {
    id: "BP-RRHH-001",
    nombre: "Proceso de Contratación",
    description: "Proceso completo de selección y contratación de personal institucional, desde la solicitud de plaza hasta la inducción del nuevo empleado.",
    category: "Recursos Humanos",
    unidadId: "rrhh",
    ownerName: "J. Ramírez",
    status: "published",
    maturityLevel: "pilot",
    currentVersion: "1.0.0",
    publishedVersion: "1.0.0",
    formIds: [
      "FORM-SOL-PLAZA-001",
      "FORM-CANDIDATOS-001",
      "FORM-PUNTAJES-001",
      "FORM-ENTREVISTA-001",
      "FORM-CONTRATO-001",
      "FORM-INDUCCION-001",
    ],
    indicatorIds: [],
    reportIds: [],
    permissionsRequired: ["hr.hiring.view", "hr.hiring.manage", "hr.hiring.approve"],
    createdAt: "2026-01-10T08:00:00.000Z",
    updatedAt: "2026-01-10T08:00:00.000Z",
    totalInstances: 3,
    activeInstances: 1,
    versions: [
      {
        id: "BPV-RRHH-001-v1",
        blueprintId: "BP-RRHH-001",
        version: "1.0.0",
        status: "published",
        changelog: "Versión inicial — cubre el ciclo completo de contratación institucional.",
        publishedAt: "2026-01-10T08:00:00.000Z",
        createdAt: "2026-01-10T08:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 3,
      },
    ],
  },

  // ── Budget Planning (Draft) ───────────────────────────────────────────────
  {
    id: "BP-VRAF-001",
    nombre: "Proceso de Planificación Presupuestaria",
    description: "Proceso anual de elaboración, revisión y aprobación del presupuesto institucional.",
    category: "Finanzas",
    unidadId: "vraf",
    ownerName: "M. Villalta",
    status: "draft",
    maturityLevel: "draft",
    currentVersion: "0.2.0",
    publishedVersion: undefined,
    formIds: ["FORM-PRESUPUESTO-001"],
    indicatorIds: ["IND-PPTO-001"],
    reportIds: [],
    permissionsRequired: ["process.create", "process.edit", "process.view"],
    createdAt: "2026-02-15T10:00:00.000Z",
    updatedAt: "2026-06-20T14:30:00.000Z",
    totalInstances: 0,
    activeInstances: 0,
    versions: [
      {
        id: "BPV-VRAF-001-v01",
        blueprintId: "BP-VRAF-001",
        version: "0.1.0",
        status: "archived",
        changelog: "Borrador inicial descartado.",
        archivedAt: "2026-04-01T08:00:00.000Z",
        createdAt: "2026-02-15T10:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 0,
      },
      {
        id: "BPV-VRAF-001-v02",
        blueprintId: "BP-VRAF-001",
        version: "0.2.0",
        status: "draft",
        changelog: "Reestructuración de etapas — se agregó revisión de Contraloría.",
        createdAt: "2026-04-05T09:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 0,
      },
    ],
  },

  // ── Purchasing Process (Published) ────────────────────────────────────────
  {
    id: "BP-COMP-001",
    nombre: "Proceso de Compras y Adquisiciones",
    description: "Proceso de solicitud, cotización, aprobación y compra de bienes y servicios institucionales.",
    category: "Compras",
    unidadId: "compras",
    ownerName: "L. García",
    status: "published",
    maturityLevel: "stable",
    currentVersion: "2.1.0",
    publishedVersion: "2.1.0",
    formIds: ["FORM-SOLICITUD-COMPRA-001", "FORM-COTIZACION-001"],
    indicatorIds: ["IND-COMP-001"],
    reportIds: ["RPT-COMP-001"],
    permissionsRequired: ["requests.create", "requests.approve", "process.view"],
    createdAt: "2025-08-01T08:00:00.000Z",
    updatedAt: "2026-03-15T16:00:00.000Z",
    totalInstances: 47,
    activeInstances: 8,
    versions: [
      {
        id: "BPV-COMP-001-v1",
        blueprintId: "BP-COMP-001",
        version: "1.0.0",
        status: "deprecated",
        changelog: "Versión original.",
        publishedAt: "2025-08-01T08:00:00.000Z",
        deprecatedAt: "2026-01-01T00:00:00.000Z",
        createdAt: "2025-08-01T08:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 31,
      },
      {
        id: "BPV-COMP-001-v2",
        blueprintId: "BP-COMP-001",
        version: "2.0.0",
        status: "deprecated",
        changelog: "Se agregó etapa de revisión por Contraloría Interna.",
        publishedAt: "2026-01-01T00:00:00.000Z",
        deprecatedAt: "2026-03-15T16:00:00.000Z",
        createdAt: "2025-12-01T10:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 12,
      },
      {
        id: "BPV-COMP-001-v21",
        blueprintId: "BP-COMP-001",
        version: "2.1.0",
        status: "published",
        changelog: "Corrección menor: límites de aprobación actualizados según resolución rectoría.",
        publishedAt: "2026-03-15T16:00:00.000Z",
        createdAt: "2026-03-10T09:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 4,
      },
    ],
  },

  // ── Maintenance Request (Deprecated) ──────────────────────────────────────
  {
    id: "BP-MANT-001",
    nombre: "Solicitud de Mantenimiento Correctivo",
    description: "Proceso de registro, diagnóstico y resolución de solicitudes de mantenimiento correctivo de infraestructura.",
    category: "Mantenimiento",
    unidadId: "mant",
    ownerName: "R. Flores",
    status: "deprecated",
    maturityLevel: "deprecated",
    currentVersion: "1.2.0",
    publishedVersion: "1.2.0",
    formIds: ["FORM-MANT-SOL-001"],
    indicatorIds: [],
    reportIds: ["RPT-MANT-001"],
    permissionsRequired: ["requests.create", "requests.view"],
    createdAt: "2025-03-10T08:00:00.000Z",
    updatedAt: "2026-05-01T08:00:00.000Z",
    totalInstances: 24,
    activeInstances: 0,
    versions: [
      {
        id: "BPV-MANT-001-v12",
        blueprintId: "BP-MANT-001",
        version: "1.2.0",
        status: "deprecated",
        changelog: "Última versión antes de migración al nuevo sistema.",
        publishedAt: "2025-09-01T08:00:00.000Z",
        deprecatedAt: "2026-05-01T08:00:00.000Z",
        createdAt: "2025-08-15T08:00:00.000Z",
        createdBy: "USR-VRAF-001",
        createdByName: "M. Villalta",
        instanceCount: 24,
      },
    ],
  },
];

export const mockInstanceSummaries: InstanceSummary[] = [
  {
    id: "INST-RH-001",
    blueprintId: "BP-RRHH-001",
    blueprintName: "Proceso de Contratación",
    nombre: "Contratación Docente — Plaza Ing. Industrial 2026",
    estado: "in_progress",
    currentStageLabel: "Evaluación Curricular",
    assigneeName: "J. Ramírez",
    createdByName: "J. Ramírez",
    startedAt: "2026-06-01T08:00:00.000Z",
    updatedAt: "2026-07-05T14:30:00.000Z",
    health: "ok",
  },
  {
    id: "INST-RH-002",
    blueprintId: "BP-RRHH-001",
    blueprintName: "Proceso de Contratación",
    nombre: "Contratación Asistente Administrativo — VRAF 2026",
    estado: "completed",
    currentStageLabel: "Inducción",
    assigneeName: "J. Ramírez",
    createdByName: "J. Ramírez",
    startedAt: "2026-03-01T08:00:00.000Z",
    updatedAt: "2026-05-15T17:00:00.000Z",
    completedAt: "2026-05-15T17:00:00.000Z",
    health: "ok",
  },
  {
    id: "INST-RH-003",
    blueprintId: "BP-RRHH-001",
    blueprintName: "Proceso de Contratación",
    nombre: "Contratación Personal de Mantenimiento 2025",
    estado: "cancelled",
    currentStageLabel: "Recepción de Candidatos",
    createdByName: "J. Ramírez",
    startedAt: "2025-11-01T08:00:00.000Z",
    updatedAt: "2025-12-10T10:00:00.000Z",
    health: "ok",
  },
  {
    id: "INST-COMP-001",
    blueprintId: "BP-COMP-001",
    blueprintName: "Proceso de Compras y Adquisiciones",
    nombre: "Compra Mobiliario Oficinas — Q3 2026",
    estado: "in_progress",
    currentStageLabel: "Aprobación de Jefatura",
    assigneeName: "L. García",
    createdByName: "L. García",
    startedAt: "2026-07-01T08:00:00.000Z",
    updatedAt: "2026-07-08T11:00:00.000Z",
    health: "warning",
    staleDays: 3,
  },
  {
    id: "INST-COMP-002",
    blueprintId: "BP-COMP-001",
    blueprintName: "Proceso de Compras y Adquisiciones",
    nombre: "Adquisición Equipos Informáticos Lab. 2026",
    estado: "blocked",
    currentStageLabel: "Cotización Proveedores",
    assigneeName: "L. García",
    createdByName: "L. García",
    startedAt: "2026-06-15T08:00:00.000Z",
    updatedAt: "2026-06-20T09:00:00.000Z",
    health: "critical",
    staleDays: 21,
  },
];
