/**
 * Google Sheets schema — one sheet (tab) per entity, never one giant sheet.
 * Mirrors web/types/entities.ts field-for-field so the two stay in sync;
 * if you add a field on one side, add it here too.
 *
 * ENTITY_SHEETS maps the wire-level entity name (as sent by
 * IAppsScriptClient) to its sheet tab name and column order. Column order
 * defines the header row written by ensureSheet_().
 */
var ENTITY_SHEETS = {
  planes: {
    sheetName: "Planes",
    columns: ["id", "nombre", "periodoInicio", "periodoFin", "descripcion"],
  },
  objetivos: {
    sheetName: "ObjetivosEstrategicos",
    columns: ["id", "planId", "nombre", "descripcion"],
  },
  proyectos: {
    sheetName: "ProyectosEstrategicos",
    columns: ["id", "objetivoId", "nombre", "descripcion", "unidadId"],
  },
  procesos: {
    sheetName: "ProcesosInstitucionales",
    columns: [
      "id",
      "proyectoId",
      "unidadId",
      "nombre",
      "tipo",
      "objetivo",
      "alcance",
      "responsableId",
      "clientesInternos",
      "clientesExternos",
      "normativaAsociada",
      "estado",
      "avancePct",
      "semaforo",
      "fechaInicio",
      "fechaLimite",
      "slaDias",
      "prioridad",
      "ultimaActualizacion",
      "createdAt",
      "deletedAt",
    ],
  },
  actividades: {
    sheetName: "Actividades",
    columns: [
      "id",
      "procesoId",
      "etapaId",
      "nombre",
      "descripcion",
      "responsableId",
      "tiempoEsperadoHoras",
      "dependenciaId",
      "prioridad",
      "estado",
      "puntoControl",
      "orden",
    ],
  },
  evidencias: {
    sheetName: "Evidencias",
    columns: [
      "id",
      "actividadId",
      "nombre",
      "tipo",
      "obligatoria",
      "estado",
      "driveFileId",
      "version",
      "responsableId",
      "fechaCarga",
      "observaciones",
    ],
  },
  indicadores: {
    sheetName: "Indicadores",
    columns: [
      "id",
      "procesoId",
      "procedimientoId",
      "nombre",
      "objetivo",
      "descripcion",
      "categoria",
      "formula",
      "unidadMedida",
      "meta",
      "valorActual",
      "frecuencia",
      "responsableId",
      "fuenteInformacion",
      "evidenciaRequeridaId",
      "dashboardDestino",
      "reporteDestino",
      "automatizacionId",
      "semaforo",
      "tendencia",
      "ultimaActualizacion",
    ],
  },
  formularios: {
    sheetName: "Formularios",
    columns: [
      "id",
      "nombre",
      "unidadId",
      "version",
      "estado",
      "schemaJson",
      "entidadGeneradaId",
      "guardadoEnBiblioteca",
      "autor",
      "fecha",
      "comentarios",
    ],
  },
  solicitudes: {
    sheetName: "Solicitudes",
    columns: [
      "id",
      "procesoId",
      "unidadId",
      "asunto",
      "solicitanteId",
      "responsableId",
      "estado",
      "fechaCreacion",
      "fechaCierre",
      "tiempoRespuestaHoras",
      "satisfaccion",
    ],
  },
  usuarios: {
    sheetName: "Usuarios",
    columns: ["id", "nombre", "email", "unidadId", "rol", "activo", "avatarInitials"],
  },
  unidades: {
    sheetName: "Unidades",
    columns: ["id", "nombre", "responsableId"],
  },
  historial: {
    sheetName: "HistorialAudit",
    columns: [
      "id",
      "entidadTipo",
      "entidadId",
      "usuarioId",
      "accion",
      "resultado",
      "fecha",
      "detalleJson",
    ],
  },

  // ── HR domain ──────────────────────────────────────────────────────────────
  empleados: {
    sheetName: "Empleados",
    columns: [
      "id",
      "usuarioId",
      "unidadId",
      "cargo",
      "departamento",
      "fechaIngreso",
      "tipoContrato",
      "estado",
      "deletedAt",
      "deletedBy",
    ],
  },
  capacitaciones: {
    sheetName: "Capacitaciones",
    columns: [
      "id",
      "nombre",
      "descripcion",
      "unidadId",
      "responsableId",
      "fechaInicio",
      "fechaFin",
      "estado",
      "modalidad",
      "deletedAt",
      "deletedBy",
    ],
  },
  evaluaciones: {
    sheetName: "Evaluaciones",
    columns: [
      "id",
      "empleadoId",
      "evaluadorId",
      "periodo",
      "estado",
      "puntajeTotal",
      "comentarios",
      "fecha",
      "deletedAt",
      "deletedBy",
    ],
  },
  solicitudesContratacion: {
    sheetName: "SolicitudesContratacion",
    columns: [
      "id",
      "unidadId",
      "cargo",
      "descripcion",
      "candidatoNombre",
      "responsableId",
      "estado",
      "fechaSolicitud",
      "fechaResolucion",
      "deletedAt",
      "deletedBy",
    ],
  },

  // ── Notifications ──────────────────────────────────────────────────────────
  notificaciones: {
    sheetName: "Notificaciones",
    columns: [
      "id",
      "usuarioId",
      "tipo",
      "titulo",
      "mensaje",
      "leida",
      "createdAt",
      "entityTipo",
      "entityId",
      "deletedAt",
    ],
  },

  // ── Workflow domain ────────────────────────────────────────────────────────
  workflowBlueprints: {
    sheetName: "WorkflowBlueprints",
    columns: [
      "id",
      "nombre",
      "version",
      "unidadId",
      "estado",
      "schemaJson",
      "createdAt",
      "createdBy",
      "updatedAt",
      "deletedAt",
      "deletedBy",
    ],
  },
  workflowInstances: {
    sheetName: "WorkflowInstances",
    columns: [
      "id",
      "blueprintId",
      "blueprintVersion",
      "blueprintName",
      "unidadId",
      "nombre",
      "estado",
      "currentStageId",
      "stagesJson",
      "assignedUsersJson",
      "auditLogJson",
      "contextDataJson",
      "createdAt",
      "createdBy",
      "updatedAt",
      "completedAt",
      "deletedAt",
      "deletedBy",
    ],
  },

  // ── Studio domain ──────────────────────────────────────────────────────────
  blueprintRegistry: {
    sheetName: "BlueprintRegistry",
    columns: [
      "id",
      "blueprintId",
      "nombre",
      "version",
      "categoria",
      "unidadId",
      "publicado",
      "autor",
      "fecha",
      "deletedAt",
      "deletedBy",
    ],
  },
  instanceSummaries: {
    sheetName: "InstanceSummaries",
    columns: [
      "id",
      "instanceId",
      "blueprintId",
      "nombre",
      "unidadId",
      "estado",
      "pct",
      "etapaActual",
      "updatedAt",
    ],
  },
};
